- README.md
[JENKINS-32493](https://issues.jenkins-ci.org/browse/JENKINS-32493)
More documentation to be added to the wiki.
@reviewbybees
> [JENKINS-32493] Update README once released.

- pom.xml
Not exactly sure what it does but @tfennelly introduced it in https://github.com/jenkinsci/workflow-plugin/pull/290.
@reviewbybees
> Allow npm.loglevel to be overridden

- pom.xml
> Additional fixes: src and doc attachment on release.

- README.md
> Update README to version 2.2

- README.md
> Update README to release 2.3

- pom.xml
> Pick JTH 2.6

- pom.xml
Ping @abayer @daniel-beck @rtyler @andresrc @jglick
> [FIX INFRA-588] Using the right repo URL

- pom.xml
> Better support for jgit in maven-release-plugin

- pom.xml
@reviewbybees esp. @jglick @abayer
> Add empty `argLine` default value

- pom.xml
And fix to windows paths for x64 and x86
@jenkinsci/code-reviewers @reviewbybees
> Configurable frontend plugin version

- pom.xml
See [JENKINS-35445](https://issues.jenkins-ci.org/browse/JENKINS-35445).
Downstream of https://github.com/jenkinsci/jenkins-test-harness/pull/22
Some additional enforcer rule added as well.
@reviewbybees
> [JENKINS-35445] Custom HtmlUnit Dependency for JTH

- pom.xml
Pick up releases with https://github.com/jenkinsci/maven-hpi-plugin/pull/38 and https://github.com/jenkinsci/jenkins-test-harness/pull/29
@reviewbybees  @jenkinsci/code-reviewers
See [JENKINS-34496](https://issues.jenkins-ci.org/browse/JENKINS-34496)
> [FIXED JENKINS-34496] Pick up releases of test-harness and hpi plugin

- pom.xml
Either show some example how to run it with current pom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/plugin-pom/32)
> Allow to run jacoco

- pom.xml
User-visible changes:
* https://github.com/jenkinsci/maven-hpi-plugin/pull/25
* https://github.com/jenkinsci/maven-hpi-plugin/pull/39
* https://github.com/jenkinsci/jenkins-test-harness/pull/30
* https://github.com/jenkinsci/jenkins-test-harness/pull/31
* https://github.com/jenkinsci/jenkins-test-harness/pull/32
@reviewbybees
> Updated maven-hpi-plugin and jenkins-test-harness

- CHANGELOG.md
- README.md
- pom.xml
> Updated test harness

- pom.xml
> Update frontend-maven-plugin to latest

- src/it/sample-plugin/postbuild.groovy
Just a better test; from a conversation on jenkinsci-dev.
@reviewbybees
> Verify that we are not bundling extra junk in WEB-INF/lib/*.jar

- pom.xml
> Updating jenkins-test-harness and maven-surefire-plugin

- pom.xml
Downstream of https://github.com/kohsuke/access-modifier/pull/3.
@reviewbybees
> Use a version of access-modifier-checker that actually works

- CHANGELOG.md
- README.md
- pom.xml
See [JENKINS-44458](https://issues.jenkins-ci.org/browse/JENKINS-44458)
@reviewbybees
> [JENKINS-44458] Disable wizard by default in `hpi:run`

- pom.xml
Cleanup after #66.
@reviewbybees
> Deleting redundant requireMavenVersion checks in profiles

- pom.xml
Complements https://github.com/jenkinsci/jenkins/pull/2656
We could make this a property, but I'm not sure there's enough of a legitimate use case.
Untested.
@jenkinsci/code-reviewers
> Annotate localizer generated classes with Restricted(NoExternalUse)

- pom.xml
[`jenkins-test-harness` changelog](https://github.com/jenkinsci/jenkins-test-harness/#228-2017-sep-26) and [`maven-hpi-plugin` changelog](https://github.com/jenkinsci/maven-hpi-plugin#21-2017-sep-26).
@reviewbybees
> Updates to jenkins-test-harness + maven-hpi-plugin

- pom.xml
Picks up:
* https://github.com/jenkinsci/jenkins-test-harness/pull/91
* https://github.com/jenkinsci/jenkins-test-harness/pull/93
* https://github.com/jenkinsci/jenkins-test-harness/pull/94
* https://github.com/jenkinsci/maven-hpi-plugin/pull/63
@jenkinsci/code-reviewers @reviewbybees
> Update jenkins-test-harness & maven-hpi-plugin

- pom.xml
Otherwise I get an IllegalArgumentException for my pom.
See: https://github.com/jenkinsci/analysis-pom-plugin/blob/3.0/pom.xml#L222
> Update animal-sniffer-maven-plugin to 1.16.

- pom.xml
Pull in latest work by @batmat and my [small round of robustness improvements and better logging for the dirty-restart simulator](https://github.com/jenkinsci/jenkins-test-harness/pull/101).
> Update test harness version

- pom.xml
Changelog: https://github.com/jenkinsci/jenkins-test-harness/blob/master/README.md#238-2018-apr-09
@reviewbybees + CC @jtnord @jglick
> [JENKINS-50598,JENKINS-50590] - Update JTH to 2.38

- pom.xml
[JENKINS-51247](https://issues.jenkins-ci.org/browse/JENKINS-51247)
Inspired by https://github.com/mojohaus/flatten-maven-plugin/issues/53#issuecomment-340366191.
> [JENKINS-51247] Simplified usage of flatten-maven-plugin

- CHANGELOG.md
Correcting the link to avoid hitting the moved here readme... 👍
> Update incrementals link

- pom.xml
Like #108. Noticed in https://github.com/jenkinsci/workflow-cps-plugin/pull/230:
```
…
[INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ workflow-cps ---
[INFO] Building jar: …/workflow-cps-plugin/target/workflow-cps-sources.jar
[INFO] 
[INFO] >>> maven-source-plugin:3.0.1:test-jar (attach-test-sources) > generate-sources @ workflow-cps >>>
[INFO] 
[INFO] --- maven-hpi-plugin:2.6:validate (default-validate) @ workflow-cps ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:display-info (display-info) @ workflow-cps ---
[INFO] Maven Version: 3.5.3
[INFO] JDK Version: 1.8.0_171 normalized as: 1.8.0-171
[INFO] OS Info: Arch: amd64 Family: unix Name: linux Version: 4.15.0-22-generic
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (display-info) @ workflow-cps --- …
```
> One more case of an unwanted forked execution

- pom.xml
Based on the advice from @jglick https://github.com/jenkinsci/pom/pull/27#discussion_r202874727
> Use mojo configuration instead of properties

- pom.xml
Picks up https://github.com/jenkinsci/incrementals-tools/pull/10.
> Updated incrementals-maven-plugin to 1.0-beta-7

- pom.xml
Picks up [various fixes](https://github.com/jenkinsci/jenkins-test-harness#241-2018-sep-21).
> jenkins-test-harness.version=2.41

- pom.xml
Amends #122 to fix an issue noted in https://github.com/jenkinsci/git-plugin/pull/621. Downstream of https://github.com/jenkinsci/jenkins-test-harness/pull/111 also.
> Create ${surefireTempDir} before running tests

- pom.xml
Picks up https://github.com/jenkinsci/jenkins-test-harness/pull/113.
> jenkins-test-harness.version=2.44

- pom.xml
https://github.com/jenkinsci/maven-hpi-plugin/pull/85 https://github.com/jenkinsci/maven-hpi-plugin/pull/84
> hpi-plugin.version=2.7

- pom.xml
Picks up https://github.com/jenkinsci/maven-hpi-plugin/pull/88, fixing #134.
> hpi-plugin.version=3.1

- pom.xml
https://github.com/kohsuke/access-modifier/compare/access-modifier-1.15...access-modifier-1.16
> access-modifier: 1.15 => 1.16

- CHANGELOG.md
- pom.xml
I pushed a snapshot: https://repo.jenkins-ci.org/snapshots/org/jenkins-ci/plugins/plugin/3.26-SNAPSHOT/plugin-3.26-20181029.184431-1.pom
So ya you can use `3.26-20181029.184431-1` to test it. 
I tested on accurev-plugin and found somethings in `hudson.tools.ToolInstallation` 😇
Lucky not blocking but it goes to show that Spotbugs is better than Findbugs.
```
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< org.jenkins-ci.plugins:accurev >-------------------
[INFO] Building Jenkins AccuRev plugin 0.7.19-SNAPSHOT
[INFO] --------------------------------[ hpi ]---------------------------------
[INFO] 
[INFO] --- spotbugs-maven-plugin:3.1.6:spotbugs (default-cli) @ accurev ---
[INFO] Fork Value is true
[java] The following errors occurred during analysis:
[java]   Error …
```
> switch to spotbugs

- .dependabot/config.yml
Closes https://github.com/jenkinsci/plugin-pom/pull/163 & Co
CC @batmat @jglick
> Dependabot: Ignore slf4j

- .dependabot/config.yml
Cf. https://github.com/jenkinsci/plugin-pom/pull/182#discussion_r267668000
Filed after seeing https://github.com/jenkinsci/plugin-pom/pull/183 again
> Ignore Core Updates for Dependabot: use the format recommended by @greysteil

- pom.xml
https://github.com/jenkinsci/jenkins-test-harness/pull/127 + https://github.com/jenkinsci/jenkins-test-harness/pull/128. Supersedes #175.
> Pick up some fixes

- .github/release-drafter.yml
See https://groups.google.com/forum/#!topic/jenkinsci-dev/dOs8YRQwQiI
CC @jglick @markewaite
> Enable Release Drafter for the repo

- CHANGELOG.md
- CONTRIBUTING.adoc
- README.md
I have added some documentation to the repository and also updated READMEs to refer GitHub releases instead
> Add CONTRIBUTING.md and Update the changelog to reference GitHub releases

- README.md
> README: Add a GitHub Release Badge to reference the changelog

- README.md
Added new badges, fixed grammar in README.MD #hacktoberfest
> Add a license badge to README

- .dependabot/config.yml
no idea if this works or not but lets give it a go...
> make dependabot ignore jenkins bom/war updates

- pom.xml
Missed it while merging on #209
> Remove another incarnation of the gmaven plugin reference

- pom.xml
https://github.com/jenkinsci/jenkins-test-harness/releases especially https://github.com/jenkinsci/jenkins-test-harness/pull/193
> jenkins-test-harness.version=2.60

- pom.xml
Mainly to pick up https://github.com/jenkinsci/maven-hpi-plugin/pull/172.
> hpi-plugin.version=3.13

- .github/FUNDING.yml
https://github.com/jenkinsci/jep/tree/master/jep/15
> [JEP-15] - Add sponsorship metadata to the repository

- pom.xml
Ref: http://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#locale
cc @timja @oleg-nenashev
> Enforce English Locale for JavaDoc Generation

- pom.xml
To pick up https://github.com/jenkinsci/jenkins-test-harness/pull/261 by @Wadeck.
> jenkins-test-harness.version=2.70

- pom.xml
For [JEP-229](https://jenkins.io/jep/229).
> [JEP-229] Created a block-MRP profile

- pom.xml
updates the localizer plugin to 1.28 (adds thread safety support for parallel builds, and messages from XML)
https://github.com/kohsuke/localizer/compare/localizer-parent-1.26...localizer-parent-1.28
> update localizer plugin

- pom.xml
> Require Maven 3.8.1

- pom.xml
Consistently use two spaces for indentation.
> Consistent indentation

- pom.xml
Implements choice 2 from [this mailing list thread](https://groups.google.com/g/jenkinsci-dev/c/89hziiKhQxs/m/_WGiA5pUCwAJ).
> Get annotation versions from core BOM

- pom.xml
Picks up https://github.com/mojohaus/extra-enforcer-rules/pull/158
> Update extra-enforcer-rules to 1.5.1

- pom.xml
https://github.com/jenkinsci/maven-hpi-plugin/pull/322#discussion_r839616144
> Introduce `jenkins.addOpens`

- pom.xml
Like #524 but for jenkinsci/maven-hpi-plugin#324.
> Introduce `jenkins.insaneHook`

- pom.xml
Like https://github.com/jenkinsci/pom/pull/215 but for `plugin-pom`.
> Skip Spotless and Checkstyle mojos in `-Pquick-build`

- pom.xml
> upgrade release plugin 3.0.0-M6

- pom.xml
This is a minor cosmetic change that puts all the version properties in one place so they are easier to read and edit.
> Group version properties together

- pom.xml
https://github.com/jenkinsci/plugin-pom/pull/631#issuecomment-1320960815
> Use `project.basedir` rather than `maven.multiModuleProjectDirectory`

- pom.xml
Removes an unused dependency forgotten in #478.
> Remove managed dependency on Animal Sniffer

- pom.xml
Forgotten in jenkinsci/jenkins#4460 & jenkinsci/jenkins#5720.
> Remove unused `hudson.udp` system property

- .github/dependabot.yml
> dependabot ignore jakarta.servlet:jakarta.servlet-api >= 5.0.0

- pom.xml
https://github.com/jenkinsci/license-maven-plugin/releases/tag/98.vd05d703fe349
> Adapt maven-license-plugin changes

- pom.xml
> Add `-proc:full` to compiler arguments

- README.md
- pom.xml
- Keep list sorted
- Use property name consistent with artifact ID
> Fixups to #801 and #805

- pom.xml
Noting jenkinsci/plugin-pom#936, as this cannot be fixed in the short term.
> Noting jenkinsci/plugin-pom#936

- .github/dependabot.yml
- Fix `yamllint` warnings
- Remove unnecessary exclusions
- Note https://github.com/jenkinsci/plugin-pom/issues/936
> Clean up `dependabot.yml`

- pom.xml
Take advantage of recent backports to the test harness.
CI build
> Upgrade test harness from 2225.2227.vfc00092c557a_ to 2225.2229.vc4c7fcb_6673c

- pom.xml
Pull in an HtmlUnit update from the backport branch.
> Update JTH from 2225.2229.vc4c7fcb_6673c to 2225.2230.v6210cb_b_827f9

- README.md
Documenting some workarounds that we have developed recently while preparing various plugins for Jetty 12.
> Document some temporary workarounds

- pom.xml
> Do not ignore `mvntest` failure

- pom.xml
See https://github.com/jenkinsci/maven-hpi-plugin/pull/668
> Require Maven 3.9.6 or later

- README.md
I hadn't seen this in the docs at the time, given its going to break a bunch of dependency update PRs are may not be adopted immediately I decided to release at 5.0
> Update version of parent pom for Java 17 being required

- README.md
- pom.xml
Tested with [workflow-cps](https://github.com/jenkinsci/workflow-cps-plugin/pull/1020)
> Add corepack support for yarn berry

- pom.xml
> Fix duplicate declaration of `maven-antrun-plugin`

- README.md
Remove extra phrase.
None.  Text change only.  Added the documentation label
> Improve phrasing of benchmark instructions

- pom.xml
https://docs.npmjs.com/cli/v11/commands/npm-ci
> This command is similar to [npm install](https://docs.npmjs.com/cli/v11/commands/npm-install), except it's meant to be used in automated environments such as test platforms, continuous integration, and deployment -- or any situation where you want to make sure you're doing a clean install of your dependencies.
Also:
> It will never write to package.json or any of the package-locks: installs are essentially frozen.
Motivated by:
- https://github.com/jenkinsci/azure-ad-plugin/pull/736#issuecomment-3372447297
- https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/998
Tested a SNAPSHOT locally and the issue with the azure-ad plugin is avoided
> Use npm ci instead of install
