- pom.xml
Yes, I know you had this originally @andresrc but I confused this with the test dep on `war-for-test`, which is what you need to run functional tests. (Prior to the `jenkins-test-harness` split, that dependency was not present in the plugin POM because it was inherited from the test harness. Now we need to declare the `war-for-test` dependency explicitly so as to override the 1.580.1 version.)
@reviewbybees
> Needed a dep on jenkins.war itself for use from hpi:run

- pom.xml
NetBeans can be configured to pass `-DskipTests=true` to many Maven runs to save time. You can override it on a particular run by changing the value to `false`, but it is harder to avoid setting the property at all. Anything gated by this property should actually check the value.
@reviewbybees esp. @andresrc
> Skip FindBugs only when skipTests=true, not when skipTests=false

- pom.xml
> Additional fixes

- pom.xml
> JTH 2.1 and Build Profiles

- pom.xml
1.580.3 was the last release of 1.580.x
Noticed this when testing builds after switching to the plugin pom - the 1.580 profile always failed to download Jenkins 1.580.4
> Fix 1.580 profile

- pom.xml
Can be useful to be able to simply globally disable jacoco using
mvn '-P!enable-jacoco' blah
Use case: the default configuration for all our SonarQube projects analysis is :
`mvn clean org.jacoco:jacoco-maven-plugin:0.7.4.201502262128:prepare-agent verify ${globalMavenProfileSocle} --batch-mode -V -U`
But that crashes with a `StackOverflowError` since this makes running two agents in different versions, like apparently the same issue explained in https://github.com/jacoco/jacoco/issues/112
> Move jacoco-m-p in an activeByDefault profile

- pom.xml
Picks up https://github.com/jenkinsci/maven-hpi-plugin/pull/28 (see note in [JENKINS-25019](https://issues.jenkins-ci.org/browse/JENKINS-25019) regarding plugins with old core deps—you will see a stack trace) and https://github.com/jenkinsci/maven-hpi-plugin/pull/29.
@reviewbybees esp. @andresrc, @kohsuke
> Use maven-hpi-plugin 1.117

- README.md
They were out of date anyway, and likely to constantly be out of date. You can always use `mvn help:effective-pom` and other tools to see actual defaults for a given version of the POM.
@reviewbybees esp. @andresrc
> Do not specify versions in README.md

- pom.xml
A test error in https://github.com/jenkinsci/maven-plugin/pull/60 led me to the realization that as of https://github.com/jenkinsci/jenkins-test-harness/pull/12 we are running tests with a version of Jetty which requires Servlet 3.1, and so we must also have that in our test classpath; else you can get errors like
```
java.lang.NoSuchMethodError: javax.servlet.http.HttpServletResponse.getStatus()I
at org.eclipse.jetty.server.handler.ErrorHandler.handle(ErrorHandler.java:112)
at org.eclipse.jetty.server.Response.sendError(Response.java:597)
at org.eclipse.jetty.server.Response.sendError(Response.java:544)
at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:117)
at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:1 …
```
> Switch to Servlet API 3.1

- pom.xml
[SUREFIRE-1138](https://issues.apache.org/jira/browse/SUREFIRE-1138)
We use `forkCount` (by default `1C`) and `reuseForks=true`; apparently this combination got broken in 2.18 and fixed in 2.19. I had noticed that my `~/.m2/settings.xml` entry
```xml
<profile>
<id>faster</id>
<activation>
<activeByDefault>true</activeByDefault>
</activation>
<properties>
<concurrency>2C</concurrency>
</properties>
</profile>
```
was not working.
@reviewbybees esp. @andresrc
> [SUREFIRE-1138] Make concurrency work

- pom.xml
Node/gulp based tests were still being run when `-DskipTests` was specified. This fixes that + adds support for a `-DskipLint` option.
@jenkinsci/code-reviewers @reviewbybees
> Honoring -DskipTests for node tests (and adding -DskipLint)

- pom.xml
Uses https://github.com/mojohaus/animal-sniffer/issues/1 to allow you to declare `java.level=8`.
@reviewbybees
> Support plugins using Java 8

- pom.xml
On OS X, ForkedBooter steals window focus, so you need to get "-Djava.awt.headless=true" on the Surefire command line to make that stop. See https://somethingididnotknow.wordpress.com/2014/07/23/forkedbooter-steals-window-focus-on-mac-os-while-maven-is-running/.
cc @reviewbybees
> Switch to java.awt.headless in Surefire

- pom.xml
This was mentioned here and never corrected: 
https://github.com/jenkinsci/plugin-pom/pull/20#discussion_r62693794
It breaks pipeline stage view builds if not corrected (with any version after plugin-pom 2.6).  Except when using hpi:run, of course.
@reviewbybees
> Fix the bug introduced in projects relying on gulp build before compile

- pom.xml
Hi,
I've encountered a problem while installing blueocean-plugin on my 32bit Debian 9 server.
You can find the full post in the [Jenkins Dev Google Group](https://groups.google.com/forum/#!topic/jenkinsci-dev/lRTz19Yv1YY).
I've solved my problem by adding the following xml to `~/.m2/repository/org/jenkins-ci/plugins/plugin/2.10/plugin-2.10.pom` :
```xml
<profile>
<id>node-classifier-linux-i386</id>
<activation>
<os>
<family>Linux</family>
<arch>i386</arch>
</os>
</activation>
<properties>
<node.download.file>node-v${node.version}-linux-x86.tar.gz</node.download.file>
<node.download.classifier />
</properties>
</profile>
```
And it's also the content of my PR (I just replaced i386 in the id by 32 bits to match the convention), because it will help if it could be integrated to the sources …
> Add nodejs for 32 bit linux

- pom.xml
Works around [SUREFIRE-1226](https://issues.apache.org/jira/browse/SUREFIRE-1226). Unfortunately means that stack frames we _did_ want trimmed are now shown, but that is the lesser evil.
@reviewbybees
> Set trimStackTrace=false to work around SUREFIRE-1226

- pom.xml
This change picks some fixes in the plugin, in particular <code>pluginArtifacts</code> parameter handling (https://github.com/gleclaire/findbugs-maven-plugin/commit/7954b94eff5c6b0524e7fe26d8f114b3c5450b86).
Diff: https://github.com/gleclaire/findbugs-maven-plugin/compare/findbugs-maven-plugin-3.0.3...findbugs-maven-plugin-3.0.4
@reviewbybees
> Update to findbugs-maven-plugin-3.0.4

- pom.xml
This PR moves the lifecycle-mapping plugin to the profiles section, so it gets only activated in an eclipse environment.
Discussion thread: https://stackoverflow.com/questions/7905501/get-rid-of-pom-not-found-warning-for-org-eclipse-m2elifecycle-mapping
Log output (before):
```
11:53:22 [INFO] Downloading: http://repo.jenkins-ci.org/public/org/eclipse/m2e/lifecycle-mapping/1.0.0/lifecycle-mapping-1.0.0.pom
11:53:22 [WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
11:53:22 [INFO] Downloading: http://repo.jenkins-ci.org/public/org/eclipse/m2e/lifecycle-mapping/1.0.0/lifecycle-mapping-1.0.0.jar
11:53:22 [WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin …
```
> suppress missing org.eclipse.m2e:lifecycle-mapping

- pom.xml
Also makes it more flexible by allowing the project to define what needs to happen for build and test + does not assume specific tools such as gulp etc.
So the profiles are now enabled via the presence of a simple marker file named `.mvn_exec_node`, Vs tying it to the existence of a framework specific file i.e. `gulpfile.js` (purposely not assuming they should be enabled via `package.json`). It does add the requirement that the project needs to define 2 [scripts](https://docs.npmjs.com/misc/scripts) in the `package.json` (named "mvnbuild" and "mvntest") that the profiles now execute (Vs executing gulp tasks).
@jenkinsci/code-reviewers @reviewbybees
> Simplify node build execution

- pom.xml
[Docs](https://jitpack.io/docs/BUILDING/#build-environment) for @jitpack build environment
Can be used prior to merge by including in your plugin POM:
```xml
<parent>
<groupId>com.github.jglick</groupId>
<artifactId>plugin-pom</artifactId>
<version>f831bd8</version>
<relativePath/>
</parent>
<groupId>org.jenkins-ci.plugins</groupId>
<repository>
<id>jitpack.io</id>
<url>https://jitpack.io</url>
</repository>
```
And if you defined a general mirror in your `~/.m2/settings.xml`:
```xml
<mirrorOf>*,!jitpack.io</mirrorOf>
```
It does work: when you have a pair of plugins with snapshot dependencies, you can use this PR (or, if merged & released, just a sufficiently new parent) on the upstream plugin; then in the downstream plugin, before committing and pushing, you add
```xml
<repository> …
```
> jitpack.io support: attach sources

- pom.xml
I noticed that uploading `*-tests.jar` to the repository was taking forever, and realized that the vast bulk of the upload size for one of these plugin releases was actually in `*-tests.jar!/test-dependencies/*.hpi`, which is never used. Fixed some other junk while I was here.
@reviewbybees
> Preconfigure test-jar executions to exclude useless stuff

- README.md
- pom.xml
#38 was broken: while the correct artifacts were produced inside `target/`, and functional tests would pass, `install:install` would copy `target/$p.jar` rather than `target/$p.hpi` to `~/.m2/repository/…/$p-$v.hpi`, allowing a malformed archive to be uploaded by `deploy` and all hell to break loose. I am not exactly sure what caused this; perhaps something funky in the `maven-hpi-plugin` lifecycle definition, perhaps just a misunderstanding of Maven phase/goal/execution semantics.
@reviewbybees esp. @stephenc (feel free to say “I told you so”)
After merge & release:
Also:
> test-jar fix

- README.md
- pom.xml
@reviewbybees 
That change switches the javadoc plugin to quiet mode
(https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#quiet)
This means it will only output errors & warnings, and will stop showing
hundreds of lines, one per file basically, for successful ones.
This is an issue for non trivially small plugins because this will somehow
hide real errors in a sea of success/happy path logs.
I still introduced a property for people who would like to keep that behaviour...
> Default to non verbose javadoc generation logs

- pom.xml
As explained in the report, I concur that this setting is not the best one.
We should have a least-surprising default, i.e. one that for instance makes test successful in most cases.
Then, for CI, or for testing, let people choose to go for more hunts.
This settings is even worse nowadays I think, because it is becoming common to slice hosts through containerization, but in most situations people would simply slice the memory and let the default settings on.
That means that you would have more often than some years ago a config with say 4 GB only, but maybe 8 or 16 cores. And that would obviously fail. I had the exact same case in the past with the GWT compiler on that very kind of agent.
In general, hence also on dev boxes like explained in the report, this is also an issue with the …
> [JENKINS-37177] surefire concurrency inappropriate default causes random build failures

- pom.xml
Update to maven-hpi-plugin 1.121 to pick up https://github.com/jenkinsci/maven-hpi-plugin/pull/46
It is fixing [JENKINS-40899](https://issues.jenkins-ci.org/browse/JENKINS-40899), needed to run tests and `hpi:run` when working on fixes for more than one plugin using snapshot dependencies between them which are pulled from a Maven snapshots repository.
> Update to maven-hpi-plugin 1.121

- pom.xml
#11 actually removed the JaCoCo profile by default, as you can see from
mvn help:active-profiles
Cf. [MNG-4917](https://issues.apache.org/jira/browse/MNG-4917).
@reviewbybees
> Do not use activeByDefault

- pom.xml
Logs like [this](https://ci.jenkins.io/job/Plugins/job/workflow-cps-plugin/job/PR-110/2/consoleFull) are hard to read in large part because we are missing https://github.com/maven-download-plugin/maven-download-plugin/pull/62.
@reviewbybees
> Upgrade download-maven-plugin

- pom.xml
Issue: https://issues.jenkins-ci.org/browse/JENKINS-42800
Jenkins Jacoco plugin > 2.0.0 (current version is 2.1.0) requires JaCoCo Maven plugin >0.7.5 as indicated on the linked issue and on the plugin page. 
For users which want to stay with old plugin would have to override this change and keep JaCoCo maven plugin < 0.7.5 with Jenkins Jacoco plugin < 2.0.0
See plugin wiki page for more information : https://wiki.jenkins-ci.org/display/JENKINS/JaCoCo+Plugin
@reviewbybees
> [JENKINS-42800] - Bump JaCoCo version to be compatible with Jenkins JaCoCo plugin data format

- pom.xml
1.3 was already having a [prerequisite on Maven 3.1.0](https://github.com/eirslett/frontend-maven-plugin/blob/frontend-plugins-1.3/frontend-maven-plugin/pom.xml#L15).
So, updating pom.xml to reflect and bumped the plugin to latest version.
@reviewbybees esp. @tfennelly @scherler @kzantow @michaelneale
> Align frontend-version with frontend-m-p prerequisite of 3.1.0

- pom.xml
@jenkinsci/code-reviewers 
@reviewbybees esp. @stephenc @aheritier @jglick @andresrc
Before:
```
mvn versions:display-plugin-updates
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Jenkins Plugin Parent POM 2.26-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- versions-maven-plugin:2.3:display-plugin-updates (default-cli) @ plugin ---
[INFO]
[INFO] The following plugin updates are available:
[INFO]   maven-clean-plugin ..................................... 2.6 -> 3.0.0
[INFO]   maven-compiler-plugin .................................. 3.3 -> 3.6.1
[INFO]   maven-dependency-plugin ............................... 2.10 -> 3.0.0
[INFO] …
```
> Bump all plugins to latest

- pom.xml
See https://github.com/jenkinsci/maven-hpi-plugin#1122-2017-apr-12
Personally especially interested in seeing https://github.com/jenkinsci/maven-hpi-plugin/pull/59 propagate for easier diagnosability when running multiple plugin builds in a Pipeline `parallel` step.
@reviewbybees
> Pick maven-hpi-plugin 1.122

- pom.xml
Since timestamped snapshots are not set to consistent versions in multimodule reactors by `mvn deploy`.
@reviewbybees
> Introducing jenkins-core.version and jenkins-war.version

- pom.xml
[JENKINS-43411](https://issues.jenkins-ci.org/browse/JENKINS-43411)
Two parts to this PR:
- Original motivation was to add support for the "yarn" package manager as an alternative to npm, which has given us many issues. This is done in 0a56287 and 	959283c.
-- There is some duplication between the configs for npm and yarn. I originally wanted to put this in a common profile, but I couldn't find a way to activate that one profile based on the presence of either marker file, as Maven only seems to support "AND" semantics when multiple files are listed.
- 87f0aef removes custom config for maven-download-plugin to download node and npm binaries. The original motivation for this config was that maven-frontend-plugin did not cache these across builds, so multi-module builds would repeatedly …
> [JENKINS-43411] add support for yarn-based builds

- pom.xml
[INFRA-1139](https://issues.jenkins-ci.org/browse/INFRA-1139)
Put load only on our own server, or (soon) a mirror thereof.
Would be nicer to define `nodeDownloadRoot` / `npmDownloadRoot` / `yarnDownloadRoot`, but that would require Artifactory to mirror those download sites in their original directory structure, and I am not sure if it can be configured to do that; whereas this PR makes no special assumptions: the layout is that of any old Maven artifact.
@reviewbybees esp. @cliffmeyers
> [INFRA-1139] Load node and npm from the Jenkins Artifactory rather than a third-party server

- README.md
- pom.xml
Downstream of https://github.com/jenkinsci/maven-hpi-plugin/pull/65. Supersedes #40.
@reviewbybees
> [JENKINS-24064] Replace war-for-test classifier with executable-war type

- pom.xml
Amends #53. Maven 3.5.0 warns you that
> The project org.jenkins-ci.plugins:plugin:pom:2.30-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
Indeed we were only requiring 3.0.4, which was incorrect.
BTW: [reference for the 3.1.0 minimum](https://github.com/eirslett/frontend-maven-plugin/blob/b5a7ef6346cb4abc8fb38f6380a57c4c569302db/frontend-maven-plugin/pom.xml#L42)
@reviewbybees
> Using requireMavenVersion, not prerequisites

- pom.xml
[JENKINS-41631](https://issues.jenkins-ci.org/browse/JENKINS-41631)
Downstream of https://github.com/apache/maven-enforcer/pull/23 and https://github.com/jenkinsci/jenkins-test-harness/pull/62.
@reviewbybees
> [JENKINS-41631] Running requireUpperBoundDeps

- pom.xml
> Need to exclude JNA from requireUpperBoundDeps for old core versions

- pom.xml
Amends #67 and intended to work with https://github.com/jenkinsci/jenkins/pull/2956.
@reviewbybees
> [JENKINS-41631] Make requireUpperBoundDeps work better with new cores

- pom.xml
By default the max memory used by surefire will depend on the system.
This however has several issues, on a machine with lots of RAM but not a
huge amount spare each surefire JVM may by default try and grab 2GB of
ram, causing (when concurrency > 1 is used) the build to run out of
memory.
756MB was chosed as it is a multple of 256MB and was enough for a large
complex project with lots of JenkinsRule type tests.
@reviewbybees
> Specify the default max memory for surefire.

- pom.xml
Downstream of https://github.com/jenkinsci/jenkins-test-harness/pull/73. Also picks up [various other changes](https://github.com/jenkinsci/jenkins-test-harness/blob/master/README.md#227-2017-sep-20). (Note that 2.26 is already in use in core.)
@reviewbybees @jenkinsci/code-reviewers
> Update jenkins-test-harness to 2.27 to pick up JENKINS-45245 fix

- pom.xml
Just picks new FindBugs patches.
Ideally we should migrate to [SpotBugs](https://github.com/spotbugs/spotbugs) when it gets stabilized.
@reviewbybees
> Update FindBugs Maven Plugin to 3.0.5

- pom.xml
I doubt any plugin cares about multicast dns discovery so just disable
it rather than giving it a non standard port (which could lead to
announcments on a public wifi network)
Also `reuseForks` is true by default so do not set it and allow users to
use the standard `-DreuseForks=false` without having to change the plugin
config.
On the same note `concurrency` is only ever used in surefires `forkCount` -
yet another non standard property.  So stop that nonsense and use
`forkCount` directly (which is initialized to concurrency for backwards
compatability)
Tested on a plugin with an updated snapshot parent using 
`mvn test` (check concurrency is one test at once)
`mvn test -Dconcurrency=4` (check concurrency if 4 at once - for backwards comparability)
`mvn test -DforkCount=4` (check …
> Don't set stupid defaults.

- pom.xml
[Changelog](https://github.com/jenkinsci/jenkins-test-harness/#231-2017-oct-17)
Most notable change is picking up https://github.com/jenkinsci/jenkins-test-harness/pull/79 to be able to test `-Djenkins.version=2.86` and later; see [JENKINS-47393](https://issues.jenkins-ci.org/browse/JENKINS-47393). (AFAIK `plugin-compat-tester` is unaffected by that since it adds synthetic deps on detached plugins.)
@reviewbybees
> jenkins-test-harness 2.31

- pom.xml
Since most plugins will use classes from Jenkins we should link the
javadoc so you can navigate to the Jenkins javadoc similar to linking to
the J2SE javadoc
Tested on a local plugin that the links to the jenkins javadoc and the Oracle J2SE javadocs are created.
@reviewbybees
> Link back to the Jenkins javadoc.

- pom.xml
Jenkins 2.0+ have used servlet api 3.x and as such attepmting to use
this API would have been cumbersome as the default would only expose 2.4
causing funky compilation.  So this moves us firmly into the 2.x era and
cleans up the use of the servlet API dependencies.
At the same time 2.60 is pretty well adopted and uses java8 so I chose
to set 2.60.1 as the baseline and use java 8 by default for compilation.
@reviewbybees
> Drop support for 1.x by default in plugin-pom

- pom.xml
As of https://github.com/jenkinsci/maven-hpi-plugin/pull/62 we need JDK 8 to run builds, so do not even let people try to build on JDK 7. (You can still specify `java.level=7` of course, or perhaps even earlier.)
@reviewbybees
> requireJavaVersion to enforce use of JDK 8+ when building

- README.md
- pom.xml
- src/it/undefined-java-level/invoker.properties
- src/it/undefined-java-level/pom.xml
- src/it/undefined-java-level/postbuild.groovy
- src/it/undefined-java-level/src/main/java/test/X.java
- src/it/undefined-java-level/src/main/resources/index.jelly
Makes #83 safer by making sure people (like me, twice) do not forget to override `java.level` when updating to a 3.x POM. Based on a trick suggested by @batmat in https://github.com/jenkinsci/durable-task-plugin/pull/53.
@reviewbybees
> Force java.level to be overridden in children

- pom.xml
[Changelog](https://github.com/jenkinsci/jenkins-test-harness/#232-2017-oct-28); in particular I want to get https://github.com/jenkinsci/jenkins-test-harness/pull/81 out there for use by a bunch of plugins to fix PCT failures from https://github.com/jenkinsci/jenkins/pull/3120.
@reviewbybees
> jenkins-test-harness.version=2.32

- pom.xml
For some reason this [defaults to `filesystem`](http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#runOrder), which is semirandom: all test suites within a package will be run as a group, but in an unpredictable order. To reduce sources of nondeterminism it is best to always run the exact same sequence of suites.
(If you isolate each test suite, as I had to do in https://github.com/jenkinsci/workflow-cps-global-lib-plugin/pull/42, it probably makes no difference. But by default we reuse test JVMs, so it is possible for one suite to somehow pollute others, in which case you could wind up with errors that do not reproduce locally.)
As of https://github.com/junit-team/junit4/pull/293 test cases within a suite are run in a deterministic order.
@reviewbybees
> surefire.runOrder=alphabetical for reproducibility

- pom.xml
- src/it/not-newest-java-level/invoker.properties
- src/it/not-newest-java-level/pom.xml
- src/it/not-newest-java-level/src/main/java/test/X.java
- src/it/not-newest-java-level/src/main/resources/index.jelly
These were recently updated to Java 8. Without this patch, a plugin normally using some pre-2.60.x baseline cannot request
```groovy
buildPlugin(jenkinsVersions: [null, '2.89'])
```
since passing `-Djenkins.version=2.89` without adding `-Djava.level=8` causes this rule to complain that Remoting and Stapler have Java 8 bytecode. The purpose of the rule is to block you from _bundling_ class files using newer bytecode than your baseline allows, not to check stuff in the core classpath, which is why we were already excluding Jenkins core artifacts.
Note that this is in some sense the opposite of https://github.com/jenkinsci/plugin-pom/pull/88#pullrequestreview-80097814.
@reviewbybees
> Add more standard enforceBytecodeVersion exclusions, for Remoting and Stapler

- pom.xml
This change makes the default configuration of FindBugs much more paranoid about potential issues. #83 bumps the Parent POM to 3.x, so I feel it is a good time to introduce it.
On the Low level there are some Not-important issues, but the experience in https://github.com/jenkinsci/envinject-lib/pull/13/ shows that otherwise we may miss real NPE risks in Jenkins.
@reviewbybees @jglick @batmat
> Make FindBugs effort and threshold configurable

- pom.xml
After https://github.com/jenkinsci/lib-task-reactor/pull/2 in 2.105, plugins using `java.level=7` need this in order to build.
@reviewbybees
> Exclude org.jenkins-ci:task-reactor from enforceBytecodeVersion

- pom.xml
Most notably picks up https://github.com/kohsuke/access-modifier/pull/7 & https://github.com/kohsuke/access-modifier/pull/10.
@reviewbybees
> access-modifier-checker 1.13

- pom.xml
- src/it/beta-fail/downstream/pom.xml
- src/it/beta-fail/downstream/src/main/java/downstream/Caller.java
- src/it/beta-fail/invoker.properties
- src/it/beta-fail/pom.xml
- src/it/beta-fail/postbuild.groovy
- src/it/beta-fail/upstream/pom.xml
- src/it/beta-fail/upstream/src/main/java/upstream/Api.java
- src/it/beta-just-testing/downstream/pom.xml
- src/it/beta-just-testing/downstream/src/main/java/downstream/NotCaller.java
- src/it/beta-just-testing/downstream/src/test/java/downstream/ApiTest.java
- src/it/beta-just-testing/invoker.properties
- src/it/beta-just-testing/pom.xml
- src/it/beta-just-testing/upstream/pom.xml
- src/it/beta-just-testing/upstream/src/main/java/upstream/Api.java
- src/it/beta-pass/downstream/pom.xml
- src/it/beta-pass/downstream/src/main/java/downstream/Caller.java
- src/it/beta-pass/invoker.properties
- src/it/beta-pass/pom.xml
- src/it/beta-pass/upstream/pom.xml
- src/it/beta-pass/upstream/src/main/java/upstream/Api.java
Downstream of https://github.com/kohsuke/access-modifier/pull/11.
@reviewbybees @jenkinsci/code-reviewers
> Allow easy consumption of beta restriction

- pom.xml
> During release:perform, we already skip tests, and there is no need to rerun FindBugs either—save a bit of time

- pom.xml
Exposes [JENKINS-50953](https://issues.jenkins-ci.org/browse/JENKINS-50953) to plugins consuming incrementals: you can
```bash
mvn incrementals:update
```
to get a newer version of some dependencies, if merged, or
```bash
mvn incrementals:update -Dbranch=jglick:experiments-JENKINS-12345
```
to get the most recent versions from some set of unmerged PRs.
> Preconfigure incrementals-maven-plugin

- pom.xml
Analogue of https://github.com/jenkinsci/pom/pull/25, though simpler in this case since the plugin POM was already (for whatever reason) suppressing the standard `release-profile` and using its own `jenkins-release` profile.
> [JENKINS-51247] Always use source:jar-no-fork, not source:jar

- pom.xml
Follows up #107; somehow missed this one. This goal is used by a minority of plugins, for example https://github.com/jenkinsci/workflow-api-plugin/pull/67.
> Also prefer test-jar-no-fork to test-jar

- pom.xml
[Changelog for 2.5 and 2.6](https://github.com/jenkinsci/maven-hpi-plugin/blob/master/README.md#26-2018-jun-01): picks up https://github.com/jenkinsci/maven-hpi-plugin/pull/80 & https://github.com/jenkinsci/maven-hpi-plugin/pull/81.
> maven-hpi-plugin 2.6

- pom.xml
As in #107/#108 I noticed Maven running a forked execution, and thus repeating some goals, and possibly running into [MNG-6405](https://issues.apache.org/jira/browse/MNG-6405). At first I thought to switch the default to `javadoc-no-fork`, but then I stopped to wonder why we were building Javadoc in these cases anyway; normally Javadoc, like sources, is attached when we are running MRP or in `produce-incrementals`. Simpler to just leave it at that and speed up developer builds. There was one use case for running Javadoc during CI builds—catching syntax errors prior to release—but for incrementalified plugins this is already handled during CI builds.
> Run Javadoc goals when producing release-like artifacts, not otherwise.

- pom.xml
Picks up https://github.com/kohsuke/access-modifier/pull/12, solving _some_ problems with `DoNotUse`. In general that mode remains unusable for most purposes—replace with `NoExternalUse`.
> access-modifier.version=1.15

- pom.xml
In order to deliver/evaluate a fix for JENKINS-52007, it would be great to have the Animal Sniffer version configurable in Plugin POM. The version is currently used in two places, so it's also helpful w.r.t project consistency
https://issues.jenkins-ci.org/browse/JENKINS-52097
@jenkinsci/java10-support @olamy @ndeloof
> [JENKINS-52097] - Update Animal Sniffer to 1.16 and make it configurable via Maven properties

- pom.xml
cc @jglick @oleg-nenashev 
This could be applied to https://github.com/jenkinsci/pom as well 👍 
Here we can see the completionGoals in use: jenkinsci/kotlin-v1-stdlib-jdk8-plugin@afc6746
> add reincrementalify to completionGoals 

- pom.xml
Picks up https://github.com/jenkinsci/incrementals-tools/pull/6.
> [JENKINS-51869] Require git-changelist-maven-extension to be 1.0-beta-4 or newer

- pom.xml
Fixes `mvn site` and a warning in the output - Currently, running `mvn site` inside any plugin project runs into an incompatibility between `maven-site` 3.6 and `maven-project-info-reports` 3.0.0:
```
[INFO] --- maven-site-plugin:3.6:site (default-site) @ plugin ---
[WARNING] Report plugin org.apache.maven.plugins:maven-project-info-reports-plugin has an empty version.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[INFO] configuring report plugin org.apache.maven.plugins:maven-project-info-reports-plugin:3.0.0
[WARNING] Error injecting: org.apache.maven.report.projectinfo.CiManagementReport …
```
> Update maven-site-plugin and add project-info-reports

- pom.xml
The default system temp dir is not a great choice for dumping stuff produced by tests, especially for CI builds running inside a Docker container which run tests calling `withDockerContainer`, which passes `--volumes-from` and then explodes because `/tmp/jenkinsTests.tmp/` (cf. `TemporaryDirectoryAllocator` & #93 + https://github.com/jenkinsci/jenkins-test-harness/pull/89) is not on a volume (when the source checkout is). The system temp dir is also used by `TestPluginManager`, the `TemporaryFolder` rule, and so on. With this change, the typical `$JENKINS_HOME` moves from say `/tmp/jenkinsTests.tmp/jenkins8944848744570102525test` to `/…/jenkinsci/some-plugin/target/tmp/jenkinsTests.tmp/jenkins8944848744570102525test`.
Ideally `WarExploder` could also be simplified to use the system temp …
> Set java.io.tmpdir to ${basedir}/target/tmp

- Jenkinsfile
- pom.xml
[SUREFIRE-1588](https://issues.apache.org/jira/browse/SUREFIRE-1588): integrates https://github.com/apache/maven-surefire/pull/197, allowing tests to be run on Debian-based systems. The alternative is
```diff
diff --git a/pom.xml b/pom.xml
index 8d85d05..9a02755 100644
--- a/pom.xml
+++ b/pom.xml
@@ -742,6 +742,8 @@
<value>${surefireTempDir}</value>
</property>
</systemProperties>
+          
+          <argLine>-Djdk.net.URLClassPath.disableClassPathURLCheck=true</argLine>
<runOrder>alphabetical</runOrder>
</configuration>
</plugin>
```
> Pick up fix of SUREFIRE-1588

- pom.xml
#130 causes JEP-200 issues in our Windows builders pending https://github.com/apache/maven-surefire/pull/198, so I am offering a safer workaround.
> A less intrusive workaround for SUREFIRE-1588

- pom.xml
- src/it/sample-plugin/postbuild.groovy
Supersedes https://github.com/jenkinsci/jenkins-test-harness/pull/71 thanks to a tip from @jtnord.
> Avoid http://www.slf4j.org/codes.html#release warning

- pom.xml
cc @jenkinsci/java11-support 
Full diff of the updated dependency: https://github.com/mojohaus/extra-enforcer-rules/compare/extra-enforcer-rules-1.0-beta-4...extra-enforcer-rules-1.1
:heavy_check_mark: Tested successfully in real conditions on the git-plugin. in https://github.com/jenkinsci/git-plugin/pull/639
> Update to extra-enforcer-rules with JDK 11 support

- pom.xml
Downstream of https://github.com/jenkinsci/maven-hpi-plugin/pull/75 . It is a more simple version of #133 which should unblock the feature while `java.level=11` is not fully supported. So you still build plugins which are formally Java 8 compliant (source/target), but you can require Java 11 due to whatever reason.
* By default, injects versions like `1.8` or `1.7`
* Can be overridden to produce `11` for Java 11. Example: https://github.com/jenkinsci/label-verifier-plugin/pull/4 and https://github.com/jenkinsci/workflow-support-plugin/pull/82 
Consumer of the pull request: https://github.com/jenkins-infra/update-center2/pull/253
> [JENKINS-20679] - Inject Minimum-Java-Version into the plugin manifest

- pom.xml
Version upgrade of the `frontend-maven-plugin`.
I believe we can safely do this globally given Blue Ocean already updated to this version a year ago: https://github.com/jenkinsci/blueocean-plugin/blob/master/pom.xml#L32 / https://github.com/jenkinsci/blueocean-plugin/pull/1464
> Update frontend-maven-plugin from 1.4 to 1.6

- CHANGELOG.md
Moves the policy from https://github.com/jenkinsci/jep/pull/221 to the changelog.
It is a temporary solution, ideally the behavior should be documented.
@jenkinsci/java11-support @daniel-beck will appreciate your opinions. Maybe it makes sense to keep `plugin.minimumJavaVersion` undocumented for now so that it's referenced only in developer guidelines for Java 11. But I rather prefer to be explicit
> [JENKINS-20679] - Changelog: Clarify usage guidelines for the properties

- pom.xml
The fix should not do much harm. I see some related errors in PCT, but I am not 100% sure we are going to fix much here. There was a big update in https://github.com/batmat/plugin-pom/commit/b96483e0608923f227aa3999bf1e143f901be123 , so let's pick the latest version just in case
See https://issues.apache.org/jira/browse/MJAR-241
> [JENKINS-55162] - Update to Maven JAR Plugin 3.1.1 to pick up the fix of MJAR-241

- pom.xml
When building a Java 11 plugin with PowerMock tests, we get a bunch of warnings for PowerMock and Mockito. I propose to define it in Plugin Management of plugin POM
https://issues.jenkins-ci.org/browse/JENKINS-55098
Demo: https://github.com/jenkinsci/saml-plugin/pull/57
> [JENKINS-55098] - Include Mockito and PowerMock to dependency management

- pom.xml
As @alecharp reported for one of his PCT tests for Java 11, objenesis 3.0.1 is actually used in PowerMock. Depending on the Mockito/PowerMock order, the enforcer was either passing or failing before. Should be fixed by this update 
https://issues.jenkins-ci.org/browse/JENKINS-55098
> [JENKINS-55098] - Update to the proper objenesis version

- pom.xml
Picks up a compatibility fix for Java 11: https://github.com/jacoco/jacoco/issues/663
https://issues.jenkins-ci.org/browse/JENKINS-54631
> [JENKINS-54631] - Update JaCoCo Plugin to 0.8.2 to pick up the Java 11 compat fixes

- pom.xml
- src/it/settings.xml
Given the adoption of [JEP-305](https://jenkins.io/jep/305) I think there is little need to include code to support [JitPack](https://jitpack.io/), which was only ever used temporarily in some since-merged PRs.
> Removing jitpack profile

- pom.xml
When running `mvn hpi:run` there was this warning:
> [WARNING] Please use `webApp/contextPath` configuration parameter in place of the deprecated `contextPath` parameter
See https://github.com/jenkinsci/maven-hpi-plugin/blob/maven-hpi-plugin-3.1/src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java#L226
> Fix warning about deprecated 'contextPath' parameter when using hpi:run

- pom.xml
-  [SUREFIRE-1541](https://issues.apache.org/jira/browse/SUREFIRE-1541) ,
-  [SUREFIRE-1588](https://issues.apache.org/jira/browse/SUREFIRE-1588) ,
-  [SUREFIRE-1608](https://issues.apache.org/jira/browse/SUREFIRE-1608) ,
SUREFIRE-1541's symptom was :
SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
happening when building the amazon-ecs-plugin with
- Maven 3.5.2
- openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
We will be able to remove the SUREFIRE-1588 workaround as well
> Upgrade of Surefire and Failsafe plugins to 3.0.0-M3

- pom.xml
See https://github.com/jenkinsci/maven-hpi-plugin#32-2019-01-16 for the changelog. 
Once it is merged, we should update https://wiki.jenkins.io/display/JENKINS/Marking+a+new+plugin+version+as+incompatible+with+older+versions to offer a better way there
@jenkinsci/java11-support @jglick
> [JENKINS-55562, JENKINS-54949] - Update Maven HPI Plugin to 3.2

- pom.xml
[JENKINS-55456](https://issues.jenkins-ci.org/browse/JENKINS-55456)
Upgrade `powermock` Junit and Mockito libraries from `2.0.0-RC.4` to `2.0.0`.
> [JENKINS-55456] Upgrade PowerMock version to 2.0.0

- pom.xml
2.138.4 includes the [SECURITY-595 fix](https://jenkins.io/security/advisory/2018-12-05/#SECURITY-595) which might break some HTTP requests. Depending on it is a straightforward way to prevent this from happening without noticing.
Based on _January_ stats, 96k out of 145k users of LTS (66%) are on 2.138.1 or newer (i.e. could trivially update to this release, or have it already). 48k out of 87k weekly users (55%) are on 2.140 or newer. (2.139 wasn't properly released.)
So this looks like a reasonable baseline for any _new_ development.
> Update core dependency to 2.138.4

- pom.xml
Cf. for details https://bugs.openjdk.java.net/browse/JDK-8212233
Seen among many repos these days.
Known already to be blocking
* https://github.com/jenkinsci/workflow-job-plugin/pull/126
* https://github.com/jenkinsci/chucknorris-plugin/pull/19
...
cc @jenkinsci/java11-support 
Deployed as `3.40-20190308.114139-1`. Demonstration of the fix upcoming.
> [JENKINS-53788] - Add profile to workaround javadoc crash on JDK 11.0.2

- pom.xml
Well, overall, it definitely still made sense! :trollface: 
Followup of https://github.com/jenkinsci/plugin-pom/pull/128 where this was introduced.
I think we can just go and rename it without fearing some kind of backward compatibility issue, given this was only released in 3.36 parent pom, and I don't expect many people to rely on that profile name.
> stopbugs => spotbugs :-)

- pom.xml
As a big fan of TestNG, this was my default choice when selecting unit test framework for my Jenkins [plugin](https://github.com/jenkinsci/lambda-test-runner-plugin). As I wanted to add an end-to-end integration test and make use of Jenkins test harness provided (JenkinsRule and BuildWatcher), I configured my Maven project to use TestNG for unit tests and JUnit for ITs. I soon realised having two test frameworks in a single project is (slightly) overengineered and moved my unit tests to JUnit. It was a surprise for me when I noticed there were now 5 more tests (InjectedTest) - failing - which were not running before when I used TestNG for my unit tests. Having Maven run both TestNG and JUnit tests has always been problematic and required sometimes "not so nice" workarounds. There are many …
> Ban TestNG dependency

- pom.xml
As per https://github.com/jenkinsci/plugin-pom/pull/173#discussion_r279916866. Despite [JDK-8219474](https://bugs.openjdk.java.net/browse/JDK-8219474) claiming some fix was backported to 11.0.3, it is still reproducible in the AdoptOpenJDK build at least:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (attach-javadocs) on project workflow-durable-task-step: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
[ERROR] …/jenkinsci/workflow-durable-task-step-plugin/src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java:374: warning: no …
```
> Fix for JDK-8212233 is not a workaround, it should have been done anyway

- pom.xml
See the discovery by @halkeye in https://groups.google.com/forum/#!topic/jenkinsci-dev/fFe3JDvvWDA
> Add `scm.url` property to enable Plugin POM changelog visualization in Dependabot pull requests for plugins

- pom.xml
given we are forking the JVM for all the tests local testing (with several plugins) has shown that we can be much faster if we do not try and do expensive JIT compilation.
Also set the initial memory to the same as the maximum as this helps too.
This will not work if the JVM does not recognise the flags (they are available in hotspot in JDK7+) but other JVMs (j9?) are unknown about.  that said the magority of plugin developers most likely use a hotspot based JVM and this is what we use in ci.jenkins.ci so I would recommend this and then let plugins whose authors build on something else adjust as nescessary.
> Optimize the Maven Surefire JVM to speedup tests

- pom.xml
The output using a newer Ant is a bit more verbose, now showing the name of the target.
**old**
```
[INFO] --- maven-antrun-plugin:1.3:run (createTempDir) @ plugin ---
[INFO] Executing tasks
[mkdir] Created dir: ***/plugin-pom/target/tmp
[INFO] Executed tasks
```
**new**
```
[INFO] --- maven-antrun-plugin:1.8:run (createTempDir) @ plugin ---
[INFO] Executing tasks
main:
[mkdir] Created dir: ***/plugin-pom/target/tmp
[INFO] Executed tasks
```
It could therefore also be an option to just define version 1.3 and don't perform the `<tasks>` to `<target>` change.
> Improve maven-antrun-plugin configuration to show names of the executed targets

- pom.xml
While "provided" makes no difference to maven in presence of "optional", it would reassure plugin writers that they too can depend on "provided" slf4j-api and rely on it being present on Jenkins.
> Use "provided" scope for slf4j-api dependency (instead of `compile`)

- README.md
- pom.xml
- src/it/beta-just-testing/pom.xml
[JENKINS-48578](https://issues.jenkins-ci.org/browse/JENKINS-48578)
See also jenkinsci/jenkins#4150
> Use BOM from Jenkins

- Jenkinsfile
- pom.xml
- src/it/benchmark/invoker.properties
- src/it/beta-fail/invoker.properties
- src/it/beta-fail/postbuild.groovy
- src/it/beta-just-testing/invoker.properties
- src/it/beta-pass/invoker.properties
- src/it/incrementals-and-plugin-bom/invoker.properties
- src/it/sample-plugin/invoker.properties
- src/it/undefined-java-level/invoker.properties
- src/it/undefined-java-level/postbuild.groovy
Clone of https://github.com/jenkinsci/maven-hpi-plugin/pull/156.
> CI improvements

- pom.xml
Without this change I couldn't run `mvn test` in the https://github.com/jenkinsci/configuration-as-code-plugin
The error was:
```
animal-sniffer-maven-plugin:1.17:check: java.lang.NoSuchMethodError: java.nio.CharBuffer.position(I)Ljava/nio/CharBuffer;
```
the documentation says to use `test` https://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/usage.html
cc @oleg-nenashev @sladyn98 @casz
> Add phase to animal-sniffer to fix mvn test

- CONTRIBUTING.adoc
- Jenkinsfile
- README.md
- pom.xml
- src/it/benchmark/invoker.properties
- src/it/benchmark/pom.xml
- src/it/beta-fail/pom.xml
- src/it/beta-just-testing/pom.xml
- src/it/beta-pass/pom.xml
- src/it/incrementals-and-plugin-bom/pom.xml
- src/it/sample-plugin/pom.xml
- src/it/undefined-java-level/pom.xml
[JENKINS-60474](https://issues.jenkins-ci.org/browse/JENKINS-60474) Streamlines the plugin pom by removing support for some older settings as per https://groups.google.com/d/topic/jenkinsci-dev/tm3F_vgK5vA/discussion
I did not remove the frontend parts for now - I have kicked that can down the road. but there are some other areas that have been streamlined.
downstream PRs
* https://github.com/jenkinsci/m2release-plugin/pull/36
* https://github.com/jenkinsci/cloudbees-folder-plugin/pull/139
changelog suggestions
* [internal] always run the integration tests in this module
* libraries that are shipped with jenkins-core now have their dependency version unconditionally managed from the [`jenkins-bom`](https://github.com/jenkinsci/jenkins/blob/jenkins-2.204.1/bom/pom.xml).  With this change …
> [JENKINS-60474] streamline the pom and support the jenkins-bom

- pom.xml
(I should have made this as draft PR, doh.)
This change keeps the dependency management for gmaven but moves the test compile and stub generation to gmavenplus.
Still a work-in-progress.  This will let us try out the change various plugin builds
pipeline-model-definition made this change recently in order to get java11 build working with minimal disruption.
[JENKINS-58028](https://issues.jenkins-ci.org/browse/JENKINS-58028)
> [JENKINS-58028] - Switch from gmaven to gmavenplus + Remove gmaven from `dependencyManagement`, gmavenplus should be used instead

- README.md
link to the repo so people can find the versions of Jenkins with a bom easier.
fortunately artifactory has some sensible ordering for versions in the index view (there was not an easy way I could find to link to a search result inside the main UI)
> Add link to show all BOM versions

- pom.xml
https://issues.jenkins-ci.org/browse/JENKINS-60694
update to 2.60 of JTH [release notes](https://github.com/jenkinsci/jenkins-test-harness/releases/tag/jenkins-test-harness-2.60) to pick up fix for jetty hang in `InjectedTest` (and any other `HudsonTestCase`)
> [JENKINS-60694] - Update Jenkins Test Harness to 2.60 with the hanging injected test fix

- pom.xml
Backports #290 and #288 , see the changelog links in these pull requests
> Plugin POM 3.x: Backport Jenkins Test Harness 2.61 and Maven HPI Plugin 3.12 updates

- pom.xml
@jglick points out we do not run tests during the release:perform phase so we may as well skip the invoker in that stage too.
> do not run invoker during release:perform

- pom.xml
Prevents duplicated Dependabot pull requests
> Introduce `powermock.version` property, update PowerMock to 2.0.7

- pom.xml
These used to be required to support timestamped snapshots, as [described here](https://github.com/jenkinsci/jep/blob/master/jep/305/README.adoc#timestamped-snapshot-issues). But this is no longer necessary as of https://github.com/jenkinsci/jenkins/pull/3394 in Jenkins 2.120, so we might as well clean up this bit of complexity and assume that `jenkins.version` is either a release version (possibly “incremental”), or `*-SNAPSHOT` for local builds.
> Removing support for jenkins-{core,war}.version properties

- .gitignore
- CONTRIBUTING.adoc
- pom.xml
- src/it/powermock/invoker.properties
- src/it/powermock/pom.xml
- src/it/powermock/src/main/resources/index.jelly
- src/it/powermock/src/test/java/test/XTest.java
#331 was actually necessary in order to pick up https://github.com/mockito/mockito/pull/1974 (see https://github.com/powermock/powermock/issues/1055), so this needs a release; and there was also a dependency tree conflict with Hamcrest. Noticed from some of the test failures in https://github.com/jenkinsci/github-oauth-plugin/pull/119.
> Actually support PowerMock

- pom.xml
https://github.com/jenkinsci/jenkins-test-harness/releases/tag/jenkins-test-harness-2.66
<details>
<summary>Release notes</summary>
> ## 📦 Dependency updates
> 
> * Bump jenkins-test-harness-htmlunit from 2.36.0-1 to 3 (#232) @dependabot
> * Bump jetty.version from 9.4.30.v20200611 to 9.4.31.v20200723 (#231) @dependabot
</details>
> Bump jenkins test harness to 2.66

- pom.xml
Reverting #320 because it introduced [SUREFIRE-1827](https://issues.apache.org/jira/browse/SUREFIRE-1827) which is very bad for Jenkins functional tests: you see no output as the test is running, only whenever it completes (or times out).
> Revert Surefire to 3.0.0-M4 to avoid SUREFIRE-1827

- pom.xml
Implements my suggestion of https://github.com/jenkins-infra/pipeline-library/pull/154#issuecomment-674991582 to avoid spammy build logs and spammy **Checks** tab annotations. See [documentation](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/javadoc.html#CHDCIBFC). On https://github.com/jenkinsci/workflow-cps-plugin/commit/261df120d1c2f228b2137c3f880a7741293ea5f2 using AdoptOpenJDK 1.8.0_265 (see why you should [not use Ubuntu’s package](https://bugs.launchpad.net/ubuntu/+source/openjdk-8/+bug/1898116)), this reduced the log spam from
```
[INFO] No previous run data found, generating javadoc.
[INFO] 
69 warnings
[WARNING] Javadoc Warnings
[WARNING] …/workflow-cps-plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsClosure2.java:34: warning: no @param for arg
[WARNING] …
```
> -Xdoclint:all,-missing

- pom.xml
See stapler/stapler#226 and [the Maven documentation](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#parameters). Once widely adopted, this would allow us to use reflection rather than ASM in Stapler for discovering method parameters. To test this change, I verified that a plugin was not able to access method parameters via reflection with the current plugin parent POM but was able to access them from a plugin parent POM with these changes. I also verified that plugins can opt out of this functionality if desired by setting `maven.compiler.parameters` to `false` in their `<properties>` section.
> Generate metadata for reflection on method parameters

- pom.xml
Akin to https://github.com/jenkins-infra/jenkins-maven-cd-action/issues/3 but for plugins which are using MRP, we do not wish to activate the `consume-incrementals` profile during the release phase because it might result in an incrementals-only artifact being included in a release version. The original conception of [JENKINS-50804](https://issues.jenkins.io/browse/JENKINS-50804) involved a new Enforcer rule active during releases that would block incremental dependencies, akin to snapshot dependencies which are already blocked, but this assumed that they could be detected via a pattern like `*-rc.*` which is not as easy as of JEP-229. Seems more straightforward to do this at the repository level.
Note that I am not exactly sure how to test this. I can verify that
```bash
mvn -P …
```
> [JENKINS-50804] Pass `-P!consume-incrementals` during `release:perform`

- .github/dependabot.yml
- pom.xml
Reverting #423 because it was producing too much noise: https://github.com/spotbugs/spotbugs/issues/1601#issuecomment-885341270
> Revert Spotbugs upgrade to 4.3.0

- pom.xml
- src/it/beta-fail/pom.xml
- src/it/beta-just-testing/pom.xml
- src/it/beta-pass/pom.xml
#424 should not have overridden the version of this library. See https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/443.
For now, just run ITs against a version of core containing https://github.com/jenkinsci/jenkins/pull/5208. The better fix will be to make `access-modifier-checker` capable of reading both the old and new index location.
> [JENKINS-66247] Do not override the version of `annotation-indexer` from core

- pom.xml
- src/it/beta-fail/pom.xml
- src/it/beta-just-testing/pom.xml
- src/it/beta-pass/pom.xml
Test environment for https://github.com/jenkinsci/lib-access-modifier/pull/52, then switched to picking up https://github.com/jenkinsci/lib-access-modifier/pull/53. Amends #424 / #426.
> [JENKINS-66247] Pick up more compatible `access-modifier-checker`

- pom.xml
- src/it/localizer/invoker.properties
- src/it/localizer/pom.xml
- src/it/localizer/src/main/java/test/X.java
- src/it/localizer/src/main/resources/index.jelly
- src/it/localizer/src/main/resources/test/Messages.properties
- src/it/localizer/src/test/java/test/XTest.java
Reported in https://github.com/jenkinsci/plugin-pom/pull/426#issuecomment-889532987. Picks up fix from https://github.com/jenkinsci/lib-access-modifier/pull/54, amending #427.
> Bogus errors about `@Restricted(NoExternalUse.class)` as in `localizer-maven-plugin`

- pom.xml
> Move node/npm download root to properties to allow easy override

- pom.xml
https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#39
One option for removing powermock tests
See example usages in:
https://github.com/jenkinsci/git-plugin/pull/1139
https://github.com/jenkinsci/jenkins/pull/5736 
(I'll file a separate PR for removing powermock and provide recommendations on alternatives)
> Add mockito-inline

- pom.xml
Added a couple of arguments to the jvm that is forked when running tests to avoid losing the focus when you run the maven tests in the background in MacOS. It's very annoying every time a fork is created you lose the focus where you were.
I manually tested with a plugin using this modified version. When the plugin run the tests, the Java icon doesn't show up anymore.
> Avoid losing the focus because ForkedBooter on MacOS when running tests

- pom.xml
Reverting #443 since it apparently breaks JaCoCo integration. Hotfix; a proper fix should
* add an IT for JaCoCo
* try to solve the original Mac-specific problem in the proper way (optionally with an IT)
> Revert #443 (`argLine` modification)

- pom.xml
Reusing forks is a cause of flakyness in tests, especially ones with `JenkinsRule`a, as Jenkins itself has many things static that may get left in a zombie like state in between tests. 
for example:
```
java.lang.IllegalThreadStateException
at java.lang.ThreadGroup.addUnstarted(ThreadGroup.java:867)
at java.lang.Thread.init(Thread.java:405)
at java.lang.Thread.init(Thread.java:349)
at java.lang.Thread.<init>(Thread.java:678)
at java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:613)
at hudson.util.DaemonThreadFactory.newThread(DaemonThreadFactory.java:47)
at hudson.util.ClassLoaderSanityThreadFactory.newThread(ClassLoaderSanityThreadFactory.java:23)
at hudson.util.NamingThreadFactory.newThread(NamingThreadFactory.java:52)
at …
```
> Do not reuse surefire (failsafe) forks for test stability

- pom.xml
Like jenkinsci/pom#196, but for `plugin-pom`.
> Use Enforcer 3.0.0 and matching extra enforcer rules

- pom.xml
Ban Apache Log4j 2.15.0-rc1 and earlier via Maven Enforcer.
> Ban vulnerable versions of Apache Log4j 2

- pom.xml
JSR 305 is in dormant status. We don't want this dependency anymore.
> Exclude JSR 305

- pom.xml
Without this exclusion, recent versions of Maven Enforcer fail against recent cores with:
```
Require upper bound dependencies error for javax.servlet:servlet-api:0 [provided] paths to dependency are:
+-org.jenkins-ci.plugins:gitlab-plugin:1.5.25-SNAPSHOT
+-org.jenkins-ci.main:jenkins-core:2.326-SNAPSHOT [provided]
+-javax.servlet:servlet-api:0 [provided] (managed) <-- javax.servlet:servlet-api:[0] [provided]
and
+-org.jenkins-ci.plugins:gitlab-plugin:1.5.25-SNAPSHOT
+-org.jenkins-ci.main:jenkins-war:2.326-SNAPSHOT [test]
+-javax.servlet:servlet-api:0 [provided] (managed) <-- javax.servlet:servlet-api:[0] [provided]
and
+-org.jenkins-ci.plugins:gitlab-plugin:1.5.25-SNAPSHOT
+-org.jenkins-ci.main:jenkins-core:2.326-SNAPSHOT [provided]
+-org.jenkins-ci.main:cli:2.326-SNAPSHOT [provided] …
```
> Exclude `javax.servlet:servlet-api`

- pom.xml
See [the release notes](https://github.com/jenkinsci/lib-access-modifier/releases/tag/access-modifier-1.26).
> Bump `access-modifier` from 1.25 to 1.27

- pom.xml
See [the release notes](https://github.com/jenkinsci/jenkins-test-harness/releases/tag/1674.v3b8b1441e939).
> Bump `jenkins-test-harness` from 1666.vd1360abbfe9e to 1674.v3b8b1441e939

- pom.xml
> Work around issues on 2.222.x, 2.235.x, and 2.289.x

- README.md
- pom.xml
- src/it/benchmark/pom.xml
- src/it/incrementals-and-plugin-bom/pom.xml
- src/it/sample-plugin/pom.xml
- src/it/undefined-java-level/pom.xml
Implements recent suggestions from the "annotation versions" mailing list thread.
> Bump Jenkins version to 2.249; clean up plugin parent POM

- pom.xml
Applies some low-risk group ID/artifact ID sorting to some (though not all) of the dependencies in the `dependencyManagement` section.
> Sort a few dependencies in the `dependencyManagement` section

- pom.xml
Noticed in workflow-job plugin `org.jenkinsci.plugins.workflow.job.WorkflowRunRestartTest.termAndKillInSidePanel` (while looking at https://github.com/jenkinsci/workflow-job-plugin/pull/235)
I don't know if it's causing any harm other than log spam but seems easy to fix.
Tested in workflow-job
> Exclude HTMLUnit from code coverage checking

- README.md
- pom.xml
[As far as I can tell](https://github.com/search?ref=simplesearch&type=Code&q=user%3Ajenkinsci+%22java.level.test%22), this feature is not used anywhere: a code search shows that in the handful of cases where `java.level.test` is explicitly set at all, it is set to the same value as `java.level`. Having a separate tunable for the Java level for tests makes the POM more complex and makes it more difficult to implement changes to the POM, so I am proposing we dispense with this feature in order to simplify the POM. If and when this feature is needed again in the future, we can always reintroduce it.
> EOL `java.level.test`

- pom.xml
Maven 3.10.0 added a feature to create missing package-info files. The feature incorrectly uses Windows-style directory separators on Windows.  Other parts of the code expect to always see Unix style directory separators.
Disable the new feature so that it does not break compilation.  See [Jenkins developer mailing list conversation](https://groups.google.com/g/jenkinsci-dev/c/077VYgtSLXo/m/6JQjJs7-AQAJ) for details.
I'm not expert enough in Maven development to create the integration test to confirm the issue is resolved.  I assume it would require a Java package that does not have a package-info file and then a check on Windows that some internal path to the generated package-info file is using Windows directory separators.
> Avoid MCOMPILER-485 in compiler plugin 3.10.0

- pom.xml
See [JENKINS-67960](https://issues.jenkins.io/browse/JENKINS-67960) and [MCOMPILER-346](https://issues.apache.org/jira/browse/MCOMPILER-346). I have run into this bug repeatedly while working on Jenkins, most recently in jenkinsci/acceptance-test-harness#733.
When compiling Jenkins code with compilation errors with Java 11, [MCOMPILER-346](https://issues.apache.org/jira/browse/MCOMPILER-346) is frequently encountered. If you encounter it with `-source 8`, you get a `NullPointerException`. If you encounter it with `-source 11`, you get an `AssertionError`. Either way, you do not get a readable message with the compilation error. Therefore, you have no idea what you need to fix in order to get the code to compile.
TBD. MCOMPILER-346 has remained open since June 28, 2018. I submitted a …
> [JENKINS-67960] Work around MCOMPILER-346

- pom.xml
#506 added a workaround for MCOMPILER-485, a bug present in Maven Compiler Plugin 3.10.0. A fix was released in 3.10.1, and we have upgraded to that release in #515, so the workaround is now obsolete and should be removed.
> Remove obsolete workaround for MCOMPILER-485

- pom.xml
This change should be functionally equivalent to the existing code, and by itself it doesn't buy us anything, but in concert with https://github.com/jenkinsci/maven-hpi-plugin/pull/323, this allows us to require Java 11 in the future without an awkward flag day.
> [JENKINS-54842] Define compiler configuration with Maven properties where possible and use Java 11 built-in functionality instead of Animal Sniffer

- pom.xml
IntelliJ IDEA is not able to run our custom Maven lifecycle mapping from `maven-hpi-plugin` (which includes a `test-runtime` mojo that configures `jenkins.addOpens` and `jenkins.insaneHook`), but as of https://github.com/JetBrains/intellij-community/pull/1976 it will be able to do late replacement of properties in `argLine` from the parent POM. This PR adds a default value of `jenkins.addOpens` for such cases. In the Maven build the `test-runtime` mojo will always fill this in with the correct value from `jenkins.war`, but this PR allows IDE builds to degrade gracefully to a setting that should work most of the time (as long as the default value specified here doesn't diverge too much from the one shipped in `jenkins.war`). To test this PR, I ran …
> Provide a default value of `jenkins.addOpens` for the benefit of IDEs

- pom.xml
See [Setting the `--release` of the Java Compiler](https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-release.html). While it does not hurt to have these set to the Java specification version, it is also not needed when `release` is in use.
> Setting `source` and `target` are unnecessary when setting `release`

- pom.xml
Fixup to #530: if we avoid defining the properties for Java 9+, we don't have to clear them.
> Avoid unnecessary defining and clearing of properties

- pom.xml
Adapting to https://github.com/jenkinsci/maven-hpi-plugin/pull/341.
> Revert JENKINS-20679 (declare the minimum Java version in the manifest)

- pom.xml
Maven HPI plugin 3.27 or later (which is included in plugin parent POM 4.40 or later) almost allows the plugin POM to support cores that require both Java 8 and Java 11 by dynamically reconfiguring `maven.compiler.release` and `maven.compiler.testRelease` (which default to 8 in order to support cores prior to 2.357) to the version of Java that `jenkins/model/Jenkins.class` was compiled with (which could be 11 with 2.357 or later): "almost" because Enforcer's bytecode version check still gets in the way if a plugin has a baseline of 2.357 or later and has a library on its classpath with Java 11 bytecode. Unfortunately, there is no easy way for Maven HPI plugin to dynamically reconfigure Enforcer for Java 11 the same way it dynamically reconfigures Maven Compiler Plugin for Java 11. So in …
> Work around JENKINS-68568

- pom.xml
See https://github.com/jenkinsci/jenkins-test-harness/pull/438 for the PR description.
> [JENKINS-48466] Provide JUnit 5 support for `JenkinsRule`

- pom.xml
https://github.com/jenkinsci/configuration-as-code-plugin/pull/2078#issuecomment-1208658342
We should still keep at least a dependency management version on junit 4.x for all plugins that continue to use `junit` annotations.
> add junit 4.x to dependency management

- pom.xml
Amending https://github.com/jenkinsci/plugin-pom/pull/614, this PR removes the default version set for yarn.
v0.23.0 was released more than 5 years ago (April 2017) towards yarn 1.x, which is EOL for several years.
Given, you'll want to use a supported version, you need to overwrite this variable anyway, with berry or the newest, and still unsupported, 1.x release.
> Remove yarn.version default

- .github/dependabot.yml
- pom.xml
The main reason we had suppressed this upgrade in https://github.com/spotbugs/spotbugs/issues/1601#issuecomment-885341270 was because of some newly-added noisy bug patterns. Those bug patterns don't appear to have been fixed in the intervening year, so suppress them globally to allow us to complete the upgrade. To test this change I ran SpotBugs on `workflow-cps` and confirmed there were tons of new violations until I added `<spotbugs.omitVisitors>FindReturnRef</spotbugs.omitVisitors>` after which there were no new violations.
> Upgrade SpotBugs from 4.2.3 to 4.7.2.1

- pom.xml
The version of the SpotBugs Maven Plugin that we are using already defines the `failOnError`, `effort`, `threshold`, and `excludeFilterFile` mojo parameters to the values of the `spotbugs.failOnError`, `spotbugs.threshold`, `spotbugs.effort`, or `spotbugs.excludeFilterFile` properties if set, with the same defaults as ours if these properties are not set (see https://github.com/spotbugs/spotbugs-maven-plugin/blob/f01a7f6b99da3d2e6dcdbddd20f0b4e4dfac73fa/src/main/groovy/org/codehaus/mojo/spotbugs/BaseViolationCheckMojo.groovy). As such it is completely redundant to declare these defaults ourselves and configure the mojo with them. To test this, I compiled the Confluence Publisher plugin with these changes and observed that the `spotbugs.failOnError` setting still took effect with the …
> Remove duplicate SpotBugs defaults

- pom.xml
Like https://github.com/jenkinsci/pom/pull/337 but for `plugin-pom`. I tested this logic as part of the other PR.
> Support a SpotBugs exclude filter file for Maven multi-module projects

- pom.xml
Objenesis is a relatively obscure library used by very few plugins: of the popular plugins, the only one I know of that consumes it directly is `git-client`. While I think it makes sense for `jenkinsci/plugin-pom` (and by extension, `jenkinsci/pom`) to manage the versions of popular libraries like Hamcrest, JUnit, and Mockito, doing so for a library like Objenesis seems less appropriate given how rarely that library is used. Better for the few consumers like `git-client` that rely on it to manage the version on their own. To test this I verified that `org.jenkinsci.plugins.gitclient.CliGitAPIImplTest` worked after this change (and after updating `git-client` to explicitly specify the Objenesis version).
> Remove managed dependency on Objenesis

- pom.xml
I find it easier to compare this `pom.xml` with that of `jenkinsci/pom` when the entries are sorted. To test this I ran `mvn clean verify` in `workflow-job` successfully with these changes.
> Sort `<pluginManagement>` entries by group ID and artifact ID

- pom.xml
Amending #632 to sort first by scope, then group ID and artifact ID.
> Sort `<dependencyManagement>` section by scope, group ID, and artifact ID

- .vscode/settings.json
- pom.xml
add profile for yarn 2 which do not support the mutex argunment anymore
Signed-off-by: Thorsten Scherler <scherler@gmail.com>
> Remove `--mutex network` argument for Yarn builds

- README.md
I removed the pointer towards Java 7 and replaced it with Java 17. We want to encourage people to go ahead and prepare their plugin for future Java versions Jenkins will depend on soon, rather than sticking to something we no longer support.
Additionally, I replaced two version references with their corresponding links, to prevent updating these sporadically.
Let's point to official resources.
> Document Java 17 support

- pom.xml
Matches https://github.com/jenkinsci/jenkins-test-harness/pull/513. Note the unusual escape syntax since we do not want the expression interpreted as a Maven property. Could probably also be done in `jenkinsci/pom` but I doubt there is a need, and that POM does not currently define any Surefire variables.
> Define `surefire.forkNumber` in Surefire JVM

- pom.xml
Building a plugin with Maven 4.0.0-alpha-3 results in (among other problems)
```
[INFO] ------------------------------------------< org.jenkins-ci.plugins:text-finder >------------------------------------------
[INFO] Building Text Finder 1.23-SNAPSHOT
[INFO]   from pom.xml
[INFO] ---------------------------------------------------------[ hpi ]----------------------------------------------------------
[WARNING] Parameter 'showDeprecation' is unknown for plugin 'maven-hpi-plugin:3.38:validate (default-validate)'
[WARNING] Parameter 'showDeprecation' is unknown for plugin 'maven-hpi-plugin:3.38:validate-hpi (default-validate-hpi)'
[WARNING] Parameter 'showDeprecation' is unknown for plugin 'maven-hpi-plugin:3.38:insert-test (default-insert-test)'
[WARNING] Parameter 'showDeprecation' is …
```
> Remove unused `showDeprecation` parameter

- pom.xml
This workaround was needed prior to the release of OpenJDK 11.0.16. We're now running 11.0.17 on Jenkins project infrastructure, so this workaround is no longer necessary.
> Remove `forceJavacCompilerUse` workaround

- pom.xml
Building plugins with Maven 4 (alpha) fails with:
> 'profiles.profile[consume-incrementals].repositories.repository.[incrementals].url' contains an expression but should be a constant. @ org.jenkins-ci.plugins:plugin:4.53
This has already been reported to Jenkins [1] and Maven [2] and was declared as an intentional change.
[1] https://issues.jenkins.io/browse/JENKINS-67878 
[2] https://issues.apache.org/jira/browse/MNG-7420
> Inline Maven property `incrementals.url` for Maven 4 support

- pom.xml
`jenkinsci/pom` defines properties for the versions of Maven plugins, which can be useful when testing a change to a Maven plugin in the contest of a Jenkins plugin build. `jenkinsci/plugin-pom` lacks this feature. This PR brings `jenkinsci/plugin-pom` up to feature parity with `jenkinsci/pom` by defining properties for any Maven plugin versions used in this POM. If the same Maven plugin is used in `jenkinsci/pom`, the same property name was used for consistency. No version numbers were changed. The integration tests should be sufficient to validate this change.
> Add properties for Maven plugin versions

- pom.xml
Side-port of jenkinsci/pom#280 to `jenkinsci/plugin-pom`. While I was here I synchronized the comments as well by removing a typo.
> Skip Yarn linting in `quick-build` profile

- pom.xml
This has been the default since the 3.x line of Maven Release Plugin, so no need to explicitly specify it here.
> Remove unnecessary `useReleaseProfile` configuration

- pom.xml
Elsewhere in this POM, the default `groupId` of `org.apache.maven.plugins` is omitted, so omit it here as well for internal consistency.
> Remove unnecessary default group ID

- pom.xml
These are core Maven plugins and their versions are managed in `jenkinsci/pom`, so I see no reason not to manage the versions here as well for consistency.
> Manage versions of `maven-assembly-plugin` and `maven-help-plugin`

- pom.xml
I can't see a reason for these excludes, since our bytecode version is Java 11 and these dependencies don't exceed Java 11 in their bytecode. To test this I successfully ran `mvn clean verify` against Text Finder with these changes.
> Remove unnecessary `enforceBytecodeVersion` excludes

- pom.xml
Fixes #702
Remove deprecated `<goal>display-info</goal>` from enforcer
According to [maven-enforcer-plugin](https://maven.apache.org/enforcer/maven-enforcer-plugin/display-info-mojo.html) this is deprecated. And in plugins we see it somewhat double currently:
> Remove deprecated `display-info`-goal

- pom.xml
While there are significant usages of `gmavenplus-plugin` that remain (e.g. `pipeline-model-definition`), there are no significant plugins that build with Maven and have Groovy tests. At least running `find . -type d -name groovy | grep src.test.groovy` in my local checkout directory with the top 250 plugins turned up no results. Better to delete this unused configuration. To test this change I successfully ran `mvn clean verify` in `pipeline-model-definition-plugin` (the only significant plugin still using `gmavenplus-plugin`) with these changes.
> Remove `test-in-groovy` execution

- pom.xml
https://spotbugs.github.io/spotbugs-maven-plugin/spotbugs-mojo.html says that it is deprecated and gives no reason for the deprecation.  Since the value was faluse, it seems safe to remove the setting.
Fixes #716
https://github.com/jenkinsci/plugin-pom/issues/716 is the issue report.
> Remove deprecated spotbugsXmlOutput setting

- README.md
- pom.xml
Supersedes https://github.com/jenkinsci/plugin-pom/pull/538. This PR enables Spotless for automatic formatting, on an opt-in basis through the presence of a `.mvn_exec_spotless` file, with the following two formatters:
- `palantir-java-format` (4-space indentation, 120 column line length)
- Sortpom (2-space indentation, POM element ordering, dependency sorting, dependency management sorting, exclusion sorting)
I have tested this configuration in a dozen or so components and believe it to be the optimal path forward.
Why do automatic formatting?
- Because it reduces "nit" comments in code reviews, allowing contributors to focus on substance rather than style.
- Because bot-authored code changes can be auto-formatted in a highly readable style.
- Because it increases consistency across all …
> Enable Spotless for automatic formatting

- pom.xml
Thanks to everyone who migrated to the new Spotless configuration and property-based activation mechanism, this short-lived and clunky file-based activation mechanism is no longer needed.
> Remove file-based Spotless activation

- pom.xml
- src/it/servlet-api/invoker.properties
- src/it/servlet-api/pom.xml
- src/it/servlet-api/src/main/resources/index.jelly
- src/it/servlet-api/src/test/java/test/ServletAPITest.java
When running tests based on `JenkinsRule`, multiple servlet APIs are available from tests classpath, then causing some issues.
For example :
`javax.servlet.http.HttpSessionBindingListener` implementation class from Jetty is compiled using 4.0 (with `default`) and test execution is using 3.1 (without `default`), then causing:
```
java.lang.AbstractMethodError: Receiver class org.eclipse.jetty.security.authentication.SessionAuthentication does not define or inherit an implementation of the resolved method abstract valueBound(Ljavax/servlet/http/HttpSessionBindingEvent;)V of interface javax.servlet.http.HttpSessionBindingListener.
at org.eclipse.jetty.server.session.Session.bindValue(Session.java:357)
```
> Upgrade from `javax.servlet-api-3.1` to `jakarta.servlet-api:4.0` and ban javax.servlet:javax.servlet-api

- pom.xml
I see no straightforward way to fix #748, so this PR simply redefines the expected behavior to be the new behavior rather than the old behavior by removing `spotless.check.skip` from any Maven profiles where it is defined, thus shifting the burden on the consumer to pass in `-Dspotless.check.skip` anywhere they were previously passing in `-Pquick-build`. While a minor burden, this seems good enough especially given the lack of any obvious alternatives.
Fixes #748.
> Remove `spotless.check.skip` from `quick-build` profile

- pom.xml
hamcrest-core is deprecated since 2019, in favor of `hamcrest` where the logic lives on since then.
Consumers are advised to replace hamcrest-x with hamcrest, if not already done.
> Replace 'hamcrest-core' with 'hamcrest'

- pom.xml
Before:
```
Caused by: org.jacoco.agent.rt.internal_4a7f17c.asm.MethodTooLargeException: Method too large: org/htmlunit/css/StyleAttributes$Definition.<clinit> ()V
at org.jacoco.agent.rt.internal_4a7f17c.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2088)
at org.jacoco.agent.rt.internal_4a7f17c.asm.ClassWriter.toByteArray(ClassWriter.java:511)
at org.jacoco.agent.rt.internal_4a7f17c.core.instr.Instrumenter.instrument(Instrumenter.java:92)
at org.jacoco.agent.rt.internal_4a7f17c.core.instr.Instrumenter.instrument(Instrumenter.java:109)
... 55 more
```
After nothing.
Note this issue doesn't cause any known issue other than spamming logs, but it is resolved again
Amends https://github.com/jenkinsci/plugin-pom/pull/777
I ran `mvn test -Dtest=InjectedTest -P enable-jacoco` before …
> Update HtmlUnit package for jacoco

- pom.xml
Prior to this junit 4.x was bringing in hamcrest-core, causing https://github.com/jenkinsci/workflow-support-plugin/pull/220 to fail:
```
mvn dependency:tree | grep -B3 -A 2 hamcrest-core
[INFO] |  |  \- com.shapesecurity:salvation2:jar:3.0.1:test
[INFO] |  +- io.jenkins.lib:support-log-formatter:jar:1.2:test
[INFO] |  +- junit:junit:jar:4.13.2:test
[INFO] |  |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] |  +- org.eclipse.jetty:jetty-security:jar:10.0.15:test
[INFO] |  |  \- org.eclipse.jetty:jetty-server:jar:10.0.15:test
```
See the docs:
https://hamcrest.org/JavaHamcrest/distributables
> Care must be taken when upgrading from Hamcrest 1.3 or earlier. Due to the change in packaging, the version conflict resolution that happens in dependency management tools won’t happen …
> Fix hamcrest versioning

- pom.xml
When running `palantir-java-format` with Java 21, the current release fails with `java.lang.NoSuchMethodError: 'com.sun.tools.javac.tree.JCTree com.sun.tools.javac.tree.JCTree$JCImport.getQualifiedIdentifier()'`. This error was fixed in https://github.com/palantir/palantir-java-format/pull/909 and released in 2.35.0; however, pending https://github.com/diffplug/spotless/issues/1774 that version is not used by Spotless. This PR adopts the workaround suggested in https://github.com/diffplug/spotless/issues/1774#issuecomment-1661007774 by pinning the version until such a time that Spotless delivers version 2.35.0 by default.
Ran `mvn clean verify` in `text-finder` before these changes on Java 11, 17, and 21. 11 and 17 passed; 21 failed with the error reported above. After these changes, …
> Upgrade `palantir-java-format` to Java 21 compatible release

- pom.xml
Mockito and Hamcrest are already customizable properties, so this makes JUnit consistent with those. The CI build should be sufficient to test this.
> Make JUnit version a customizable property

- pom.xml
- src/it/settings.xml
I cannot see a reason to continue using `mrm-maven-plugin`. Based on https://www.mojohaus.org/mrm/mrm-maven-plugin/examples/invoker-tests.html it seems the reason for using it was originally
> to allow the integration tests of a Maven Plugin to be run against a test local repository thereby ensuring that the plugin does not get installed into the local repository until after the integration tests have been confirmed as passing
but I just ran `mvn clean verify` and my local `~/.m2` repository did not seem to get polluted, so I don't think this is a concern anymore now that we are configuring `maven-invoker-plugin` with `localRepositoryPath`.
For what it's worth, I asked Maven developer Tamás Cservenák to audit `maven-hpi-plugin` a few months back, and here is what he had to say:
> I'd …
> Remove `mrm-maven-plugin`

- pom.xml
- src/it/settings.xml
Reverting jenkinsci/plugin-pom#828, since I didn't notice in the original build that it introduced a bunch of new warnings:
```
13:48:22  [INFO] [INFO] Artifact org.apache.maven:maven-parent:pom:39 is present in the local repository, but cached from a remote repository ID that is unavailable in current build context, verifying that is downloadable from [central (https://repo.maven.apache.org/maven2, default, releases)]
13:48:22  [INFO] [INFO] Artifact org.apache.maven:maven-parent:pom:39 is present in the local repository, but cached from a remote repository ID that is unavailable in current build context, verifying that is downloadable from [central (https://repo.maven.apache.org/maven2, default, releases)]
13:48:22  [INFO] [INFO] Artifact org.apache:apache:pom:29 is present in the local …
```
> Revert "Remove `mrm-maven-plugin`"

- pom.xml
PowerMock tends to wreak havoc when it is on the classpath at the same time as Mockito in newer Java versions, so ban this dependency. I have not banned `org.powermock:powermock-reflect` since it is actually safe and some plugins (like Blue Ocean) depend on it. But I have banned every other PowerMock artifact.
I tested this in context in a plugin that used `powermock-reflect`. Attempting to add another PowerMock package caused (as expected):
```
Rule 4: org.apache.maven.enforcer.rules.dependency.BannedDependencies failed with message:
org.jenkins-ci.plugins:build-blocker-plugin:hpi:1.7.10-SNAPSHOT
org.powermock:powermock-module-junit4:jar:2.0.9 <--- banned via the exclude/include list
```
```[tasklist]
```
> Add PowerMock to banned dependencies

- pom.xml
While writing https://github.com/jenkinsci/jep/pull/400#issuecomment-1789790624 I realized that there was no good reason not to define `maven.compiler.testRelease` in terms of `maven.compiler.release`. When defined in this way, a consumer that wants to use two different values can still do so, but a consumer that simply wants to change bytecode generation from Java 11 bytecode to e.g. Java 17 bytecode now only has to change one property instead of two, which is a net benefit. As of this PR, there is just one occurrence of "11" in the POM, which is the `maven.compiler.release` property, and this now becomes the only knob that needs to be tuned to decide on which bytecode should be generated.
In `text-finder-plugin` I applied
```xml
diff --git a/pom.xml b/pom.xml
index 51a56f5..17b6a0d …
```
> Define `maven.compiler.testRelease` in terms of `maven.compiler.release`

- pom.xml
Reverts jenkinsci/plugin-pom#856 because this new version results in dozens of noisy SpotBugs violations of questionable value.
> Revert "Bump com.github.spotbugs:spotbugs-maven-plugin from 4.7.3.6 to 4.8.1.0"

- pom.xml
See [JENKINS-65650](https://issues.jenkins.io/browse/JENKINS-65650), [JENKINS-66060](https://issues.jenkins.io/browse/JENKINS-66060), and [JENKINS-72353](https://issues.jenkins.io/browse/JENKINS-72353). Prevent a common mistake by turning it into a compilation error.
Verified that `build-pipeline-plugin` could be compiled in its current (broken) state before this PR and threw an error after this PR, and that the error went away after ensuring the Jenkins test harness was in test scope.
> Ban Jenkins test harness in compile scope

- pom.xml
This change is meant to work in tandem with https://github.com/jenkinsci/maven-hpi-plugin/pull/578. Without it, it is essentially a no-op (unless a user enables one of the new profiles explicitly e.g. via `-Pjava-level-17`)
These will get used by IDEs (e.g. IDEA IntelliJ) to set the appropriate java level if it differs from the default java level defined in the pom file.
In practice, `maven-hpi-plugin` will generate and manage the files used as activation markers for these profiles, depending on the java level required by the jenkins version the plugin required.
```[tasklist]
```
> Add java level profiles for java 17 and java 21

- pom.xml
Corresponds to https://github.com/jenkinsci/pom/pull/537 per https://github.com/jenkinsci/pom/pull/537#pullrequestreview-1980676329
Used a local snapshot of this change on `matrix-auth` plugin with a change that would fail Spotless in the released plugin POM 4.80 with `-Pquick-build`, passed after.
> [JENKINS-72956] Skip Spotless in quick-build profile

- pom.xml
Until ASM is removed from Jenkins core, we have a temporary situation where ASM is provided both by core (deprecated) and by the plugin system (in anticipation of the aforementioned removal), which can create Enforcer errors. Ignore these for now to avoid build spam until such a time that ASM is removed from core and widely deployed in an LTS release.
Reproduced the problem described in the PR code comments in JaCoCo plugin by attempting to upgrade it to the latest BOM. Could no longer reproduce after these changes.
Fixes jenkinsci/bom#3098
> Work around ASM require upper bound dependencies error

- pom.xml
I removed these exclusions and verified that `mvn dependency:tree -Dverbose` in a plugin remained the same before and after this PR against both weekly and the earliest supported version (2.361), proving these lines of code are dead code.
> Remove dead code

- pom.xml
Pull in https://github.com/jenkinsci/jenkins-test-harness/pull/791 which was backported to the Java 11 branch of the test harness.
> Upgrade HtmlUnit from 4.2.0 to 4.3.0

- pom.xml
Reverts jenkinsci/plugin-pom#1001
This release requires Java 17 or newer, while the plugin parent POM still supports Java 11.
> Revert "Bump org.jenkins-ci.tools:maven-hpi-plugin from 3.57 to 3.58"

- .github/dependabot.yml
- README.md
- pom.xml
- src/it/benchmark/pom.xml
- src/it/beta-fail/pom.xml
- src/it/beta-just-testing/pom.xml
- src/it/beta-pass/pom.xml
- src/it/cd-plugin/pom.xml
- src/it/incrementals-and-plugin-bom/pom.xml
- src/it/localizer/pom.xml
- src/it/sample-plugin/pom.xml
- src/it/servlet-api/pom.xml
In draft until EE 9 is delivered in an LTS release.
`mvn clean verify`
Fixes #936
Fixes #918
> [JENKINS-73339] Require Java 17 and Jetty 12 (EE 9) for plugin development

- README.md
- pom.xml
I often find myself forgetting to apply spotless before committing.
On some repositories, I have set up a pre-commit git hook running `mvn spotless:check`. However, this has to be set up on each repository that has spotless check enabled, and disabled on those which don't.
I think this goes one step further, by defining a conventional maven profile `may-spotless-apply` that will run `spotless:apply` *only* if spotless is enabled for the given repository.
This allows any user to incorporate `-Pmay-spotless-apply` as part of their usual build command (or defined in their maven settings active profiles section), and have `spotless:apply` automatically called if the project has it enabled.
Example Maven `settings.xml`
```
<settings>
[...]
<activeProfiles>
[...] …
```
> Add 'may-spotless-apply' profile

- README.md
- pom.xml
Fixes https://github.com/jenkinsci/plugin-pom/issues/874
Restores the ability to use Jenkins to report test failures (broken in https://github.com/jenkinsci/plugin-pom/pull/1008) and implements support for linting.
See also discussion in https://github.com/jenkinsci/plugin-pom/pull/1015#issuecomment-2368535480 where it was decided that the restoring of the support will be opt-in to ensure that by default plugins builds will not silently fail on frontend test / lint failures.
Tested with a local SNAPSHOT in https://github.com/jenkinsci/workflow-cps-plugin/pull/935
> Add docs for frontend integration + opt-in for Jenkins integration

- pom.xml
At least until https://github.com/jenkinsci/jenkins/pull/9827 is shipping and backported.
See https://github.com/jenkinsci/workflow-job-plugin/pull/471.
> Work around jenkinsci/plugin-pom#1032

- README.md
The documentation for the marker files missed the leading dot.
They were introduced by #1016.
> Fix doc since marker files are dotfiles

- pom.xml
This PR fixes #903.
This PR adds support for the bridge-method-injector plugin in the Jenkins plugin-pom. By including it, any Jenkins plugin that uses this parent pom will automatically inherit the configuration for this plugin
- Ran **mvn clean verify** on the plugin-pom project to ensure the built completed successfully
- To verify the functionality, I tested a downstream plugin(Display URL API Plugin), by updating its parent pom to the locally built one. The plugin built successfully using the updated parent
- Asserted that the downstream project’s effective pom (**mvn help:effective-pom**) includes the bridge-method-injector plugin(inherited from the parent)
> Add `bridge-method-injector` support

- pom.xml
See [JEP 451](https://openjdk.org/jeps/451).
While testing `ec2-plugin` recently, I saw
```
Mockito is currently self-attaching to enable the inline-mock-maker. This will no longer work in future releases of the JDK. Please add Mockito as an agent to your build as described in Mockito's documentation: https://javadoc.io/doc/org.mockito/mockito-core/latest/org.mockito/org/mockito/Mockito.html#0.3
WARNING: A Java agent has been loaded dynamically (/home/basil/.m2/repository/net/bytebuddy/byte-buddy-agent/1.15.11/byte-buddy-agent-1.15.11.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading …
```
> Prepare for JEP 451

- pom.xml
I ran into some cases where the formatting of `com.diffplug.spotless:spotless-maven-plugin` simply did not produce satisfying results.
There is a [feature](https://github.com/diffplug/spotless/tree/main/plugin-maven#spotlessoff-and-spotlesson) that allows comments to toggle spotless formatting on and off (disabled by default):
```java
public void doNotFormatThisPlease() {
// spotless:off
...
// spotless:on
}
```
While I can override the config in my plugin `pom.xml` I don't see a reason to not enable the feature by default here.
Manually verified that changes have no impact if the feature is not being used.
> Enable `toggleOffOn` feature for spotless

- pom.xml
Downstream of https://github.com/jenkinsci/maven-hpi-plugin/pull/741. Fixes https://github.com/jenkinsci/bom/pull/5000#issuecomment-2852005108 by reimplementing #1130 in `maven-hpi-plugin`, thus preserving the calling convention expected by PCT.
See https://github.com/jenkinsci/maven-hpi-plugin/pull/741.
> Set `jenkins.javaAgent` in `TestRuntimeMojo`

- pom.xml
Most recent release of the formatter.
https://github.com/palantir/palantir-java-format/releases lists the releases.
* Confirmed that `mvn clean verify` passes
* Confirmed that 10+ plugins do not alter formatting with Java 21 when using this version
> Use palantir Java format 2.72.0

- pom.xml
[Palantir Java Format 2.73.0](https://github.com/palantir/palantir-java-format/releases/tag/2.73.0) released last week.
The git client plugin use of `spotless` needs the Palantir Java Format upgrade to 2.73.0 in order to run `spotless` with Java 25.  The Palantir Java Format upgrade does not seem to be required for Jenkins core to run `spotless` with Java 25.
Matching pull request in the core pom:
* https://github.com/jenkinsci/pom/pull/702
Confirmed that `mvn spotless:apply` fails with Java 25 EA build 28 on git client plugin without this change.
Confirmed that `mvn spotless:apply` succeeds with Java 25 EA build 28 on git client plugin with this change.
Confirmed that `mvn spotless:apply` makes no formatting changes in git client plugin with this change.
> Use Palantir Java Format 2.73.0

- pom.xml
With https://github.com/jenkinsci/bridge-method-injector/pull/124 comes a new Maven Group ID.
> Upgrade `bridge-method-injector` from 1.31 to 1.32

- pom.xml
Picks up https://github.com/jenkinsci/maven-hpi-plugin/pull/771. Dependabot will file this eventually, but I'd like to get a release out to be able to use the new options in some plugins and in https://github.com/jenkinsci/archetypes/pull/844.
Part of https://github.com/jenkinsci/maven-hpi-plugin/issues/557.
Untested
> Bump org.jenkins-ci.tools:maven-hpi-plugin from 3.66 to 3.1746.v2e9fe7dc4d95
